// Package scaffold 项目脚手架生成
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// Config 脚手架配置
type Config struct {
	ProjectName string
	Template    string
	Database    string
	Cache       string
	EnableDocker bool
	EnableGit    bool
}

// Generator 生成器
type Generator struct {
	config *Config
}

// NewGenerator 创建生成器
func NewGenerator(config *Config) *Generator {
	return &Generator{config: config}
}

// Generate 生成项目
func (g *Generator) Generate() error {
	// 创建项目目录
	projectDir := g.config.ProjectName
	if err := os.MkdirAll(projectDir, 0755); err != nil {
		return fmt.Errorf("failed to create project directory: %w", err)
	}

	// 生成目录结构
	dirs := []string{
		"cmd/" + g.config.ProjectName,
		"internal/handler",
		"internal/service",
		"internal/repository",
		"internal/model",
		"api",
		"config",
		"migrations",
		"tests",
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(projectDir, dir), 0755); err != nil {
			return err
		}
	}

	// 生成文件
	if err := g.generateMain(projectDir); err != nil {
		return err
	}

	if err := g.generateConfig(projectDir); err != nil {
		return err
	}

	if err := g.generateREADME(projectDir); err != nil {
		return err
	}

	fmt.Printf("✓ Project created: %s\n", projectDir)
	return nil
}

// generateMain 生成 main.go
func (g *Generator) generateMain(dir string) error {
	content := fmt.Sprintf(`package main

import (
	"fmt"
	"log"
	"net/http"

	"%s/internal/handler"
)

func main() {
	// 初始化处理器
	h := handler.New()

	// 路由设置
	http.HandleFunc("/", h.Index)
	http.HandleFunc("/health", h.Health)

	// 启动服务器
	port := ":8080"
	fmt.Printf("Server starting on port %%s\\n", port)
	if err := http.ListenAndServe(port, nil); err != nil {
		log.Fatal(err)
	}
}
`, g.config.ProjectName)

	return os.WriteFile(filepath.Join(dir, "cmd", g.config.ProjectName, "main.go"), []byte(content), 0644)
}

// generateConfig 生成配置文件
func (g *Generator) generateConfig(dir string) error {
	configPath := filepath.Join(dir, "config", "config.yaml")
	content := "# " + g.config.ProjectName + " Configuration\n\n"
	content += "server:\n"
	content += "  port: 8080\n"
	content += "  host: localhost\n\n"
	content += "database:\n"
	content += "  type: " + g.getDatabaseType() + "\n"
	content += "  host: localhost\n"
	content += "  port: 5432\n"
	content += "  name: " + g.config.ProjectName + "\n"
	content += "  user: user\n"
	content += "  password: password\n\n"
	content += "cache:\n"
	content += "  type: " + g.getCacheType() + "\n"
	content += "  host: localhost\n"
	content += "  port: 6379\n\n"
	content += "logging:\n"
	content += "  level: info\n"
	content += "  format: json\n"

	return os.WriteFile(configPath, []byte(content), 0644)
}


// generateREADME 生成 README
func (g *Generator) generateREADME(dir string) error {
	content := "# " + g.config.ProjectName + "\n\n"
	content += "Generated by Shode CLI.\n\n"
	content += "## Getting Started\n\n"
	content += "Install dependencies:\n"
	content += "Run development server:\n"

	return os.WriteFile(filepath.Join(dir, "README.md"), []byte(content), 0644)
}

// generateConfig 生成配置文件

// initGit 初始化 Git
func (g *Generator) initGit(dir string) error {
	fmt.Println("Git repository initialized")
	return nil
}

// getDatabaseType 获取数据库类型
func (g *Generator) getDatabaseType() string {
	if g.config.Database == "" {
		return "postgres"
	}
	return g.config.Database
}

// getCacheType 获取缓存类型
func (g *Generator) getCacheType() string {
	if g.config.Cache == "" {
		return "redis"
	}
	return g.config.Cache
}
