#!/bin/bash
# Simple WebSocket test indicator

echo "================================"
echo "WebSocket Test Information"
echo "================================"
echo ""
echo "Server running at: ws://localhost:8096/ws"
echo ""
echo "Test Options:"
echo ""
echo "1. Browser Test:"
echo "   - Open examples/websocket-test-client.html in your browser"
echo "   - Click 'Connect' button"
echo "   - Type messages and click 'Send'"
echo ""
echo "2. Command Line Tools:"
echo "   - Install websocat: brew install websocat"
echo "   - Test: websocat ws://localhost:8096/ws"
echo ""
echo "   - Or install wscat: npm install -g wscat"
echo "   - Test: wscat -c ws://localhost:8096/ws"
echo ""
echo "3. Browser Console:"
echo "   const ws = new WebSocket('ws://localhost:8096/ws');"
echo "   ws.onopen = () => console.log('Connected');"
echo "   ws.onmessage = (e) => console.log('Received:', e.data);"
echo "   ws.send('Hello WebSocket!');"
echo ""
echo "Current server status:"
ps aux | grep "[s]hode run.*websocket-chat" | awk '{print "  PID:", $2, "MEM:", $4"%", "Started:", $9}'
echo ""
echo "================================"
